update quickstart
cmontella/docs pull request #8
Opened 2017-06-06 00:57 UTC by cmontella

2017-06-06 19:56 UTC, joshuafcole requested changes

2017-06-06 19:56 UTC, joshuafcole commented on install.md
>  Install [Node](https://nodejs.org/en/download/) for your platform, then clone and build the Eve starter repository:
Let's include a link here to the eve starter repo, theoretically someone without git could download just a zip file here, or people who prefer ssh can grab the ssh url.

2017-06-06 19:56 UTC, joshuafcole commented on install.md
> +
formatting is funny here.

2017-06-06 19:56 UTC, joshuafcole commented on quickstart.eve.md
> +Searches find records that matches the supplied pattern, in this case records tagged greeting with a message attribute. You use these results to create new records. In this block, we create a `#ui/te
I'd mention that the ui library looks for records tagged ui/text and draws them as DOM elements in the browser.

2017-06-06 19:56 UTC, joshuafcole commented on quickstart.eve.md
If we want to use this example, you need to include another 2 line block to commit `[#system/timer #time resolution: 1000]` or it won't work. We don't want a non-functional block in the quickstart.

2017-06-06 19:56 UTC, joshuafcole commented
Oh, we should also include a blurb at the beginning of the quickstart directing users to the install/run page if they don't already have a running instance of the eve starter.

2017-06-21 00:56 UTC, joshuafcole requested changes

2017-06-21 00:56 UTC, joshuafcole commented on quickstart.eve.md
> +Eve documents are written in Markdown. Eve code is written in blocks, delinated by Markdown code fences (matching pairs of ``` or ~~~ surrounding a section of code). These blocks of code search for a
delinated -> delineated

2017-06-21 00:56 UTC, joshuafcole commented on quickstart.eve.md
> +The record committed by this block is tagged `#greeting`, and has an attribute "message" with the value "hello world". Tags are attributes like any other, their special syntax notwithstanding. We enc
should we explicitly call out `#cow` -> `tag: "cow"` ?

2017-06-21 00:56 UTC, joshuafcole commented on quickstart.eve.md
> +Blocks in Eve react automatically to changes in data. When a record changes, any bound records are automatically updated. We can see this in action by outputting the current time. First we create a t
We should maybe link to the docs system bit once that's added. @ibdthor I forgot that we need to document that one. Thankfully it's basically just timers atm.

2017-06-21 00:56 UTC, joshuafcole commented on quickstart.eve.md
> +The identity of a record is determined by its attribute/value pairs. Two records with the same attributes and values are identical in Eve. We included the `event` attribute in the `#clicked` record t
"are identical in Eve" "are the same record in Eve".

2017-06-21 03:58 UTC, cmontella commented on quickstart.eve.md
> +The record committed by this block is tagged `#greeting`, and has an attribute "message" with the value "hello world". Tags are attributes like any other, their special syntax notwithstanding. We enc
I think Rob was against this in an earlier discussion, since it muddied the waters.

2017-06-21 04:02 UTC, closed without merging